export enum ResponseErrorMessage {
  TRIVIA_QUESTION_ERROR = 'TRIVIA_QUESTION_ERROR',
  TRIVIA_USER_ERROR = 'TRIVIA_USER_ERROR',
  QUESTION_NOT_FOUND = 'QUESTION_NOT_FOUND',
  OPTION_NOT_FOUND = 'OPTION_NOT_FOUND',
  QUESTION_ALREADY_HAVE_ANSWER = 'QUESTION_ALREADY_HAVE_ANSWER',
}
