export const PermissionsMap = {
  GET_TRIVIA: 'GET_TRIVIA',
  LIST_TRIVIA: 'LIST_TRIVIA',
  CREATE_TRIVIA: 'CREATE_TRIVIA',
  DELETE_TRIVIA: 'DELETE_TRIVIA',
  GET_QUESTION: 'GET_QUESTION',
  LIST_QUESTIONS: 'LIST_QUESTIONS',
  CREATE_QUESTION: 'CREATE_QUESTION',
  DELETE_QUESTION: 'DELETE_QUESTION',
  ASSIGN_USER_TRIVIA: 'ASSIGN_USER_TRIVIA',
  CREATE_USER: 'CREATE_USER',
  GET_TRIVIA_RANKING: 'GET_TRIVIA_RANKING',
  GET_TRIVIA_SCORE: 'GET_TRIVIA_SCORE',
  ANSWER_TRIVIA: 'ANSWER_TRIVIA',
} as const;

export type PermissionsDomain =
  (typeof PermissionsMap)[keyof typeof PermissionsMap];
