export enum ResponseErrorMessage {
  PASSWORD_NOT_VALID = 'PASSWORD_NOT_VALID',
  PASSWORDS_NOT_MATCH = 'PASSWORDS_NOT_MATCH',
  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',
  ERROR_CREATING_PASSWORD = 'ERROR_CREATING_PASSWORD',
}
