version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: talatrivia
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: talana
      POSTGRES_PASSWORD: dGFsYW5hLXBhc3N3b3Jk
      POSTGRES_DB: talana
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
