version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: talatrivia
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
